package com.sxt.web.common.model;

import com.sxt.web.common.model.base.BaseBlog;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 * FissionFileSystem model.
 * 数据库字段名建议使用驼峰命名规则，便于与 java 代码保持一致，如字段名： userId
 */
@SuppressWarnings("serial")
public class FissionFileSystem extends BaseBlog<FissionFileSystem> {
	
	public static final FissionFileSystem me = new FissionFileSystem();
	
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<FissionFileSystem> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from fission_filesystem.file order by fileId asc");
	}
}


