package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {

	public static void mappingDemoDB(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
	}

	public static void mappingFissionFilesystemDB(ActiveRecordPlugin arp) {
		arp.addMapping("file", "fileId", FissionFileSystem.class);
	}

}

